name: Build BackroomsLite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
 run:
  working-directory: .github

jobs:
  build:
    runs-on: ubuntu-latest
    container: rockylinux:9
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set up JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: adopt
          java-version: 17
      - name: Update Repo
        run: yum -y install https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/e/epel-release-9-4.el9.noarch.rpm
      - name: Install required dependencies
        run: yum repolist -y && dnf search screen -y && dnf -y install screen && dnf -y install git && dnf -y install maven 
      - name: Install xBuild
        run: yum update -y && dnf install python3 && dnf install https://yum.poixson.com/latest.rpm -y && dnf install pxn-testing-release -y && dnf install xbuild -y
      - name: Clone dependencies project
        run: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts && xbuild --pp
      - name: Compile project
        run: xbuild --dev
      - name: Upload BackroomsLite
        uses: actions/upload-artifact@v3.0.0
        with:
          name: BackroomsLite
          path: "pxnBackroomsLite/target/"
        
