name: Build BackroomsLite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
 run:
  working-directory: .github

jobs:
  build:
    runs-on: ubuntu-latest
    container: rockylinux:9
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set up JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: adopt
          java-version: 17
      - name: Install xBuild
        run: yum update -y && dnf install python3 && dnf install https://yum.poixson.com/latest.rpm -y && dnf install pxn-testing-release -y && dnf install xbuild -y
      - name: Clone dependencies
        run: xbuild --pp
      - name: Compile All project
        run: xbuild --dev
      - name: Upload BackroomsLite
        uses: actions/upload-artifact@v3.0.0
        with:
          name: LimboQueue
          path: "pxnBackroomsLite/target/"
        
